### PR TITLE
The native2ascii-maven-plugin moved to production-ready plugins

### PR DESCRIPTION
**Pull request by dmatej**
I need also someone who has permissions to change the github repo settings - the gh_pages branch is there, but probably is not visible for browsers as the website. See https://github.com/mojohaus/mojohaus.github.io/issues/10#issuecomment-1577222143 - same probably applies for other repositories.

### CODE REVIEW

**Comment by dmatej** [comment]
(another possibility is to make an "Owner" as I am just "Member")

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
@ hboutemy @olamy could You help with setup?

**Review by slawekjaranowski — APPROVED** [review]

**Comment by olamy** [comment]
@slachiewicz sorry, I didn't see the ping until today (TooManyNotificationsException). 
Is everything setup now?

**Comment by slawekjaranowski** [comment]
@olamy still 404 - https://www.mojohaus.org/native2ascii-maven-plugin

**Pull request merged**
