### PR TITLE
Add PGP key for stefanseifert

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Comment by bmarwell** [comment]
Hi, please feel free to merge. The checks went well.

**Comment by stefanseifert** [comment]
thanks! - i've not the access rights to merge, though

**Comment by slachiewicz** [comment]
@stefanseifert  I merged that change, but I would like to ask about reason - why you need this hey here?

**Comment by rfscholte** [comment]
I think this commit should be reverted: `KEYS` should only contain keys of mojohaus committers, and they have the rights to do so.
This is what one would expect when verifing with mojohaus KEYS.

**Comment by stefanseifert** [comment]
i've commit rights to one of the mojohaus repos and did the last two releases of it: https://github.com/mojohaus/build-helper-maven-plugin - not to any other repos

**Comment by rfscholte** [comment]
Do you know who gave you access? I think something went wrong, because I don't think mojohaus should give access on repo level, way too hard to maintain.

**Comment by stefanseifert** [comment]
this is the mail thread: https://groups.google.com/g/mojohaus-dev/c/URMg1__Mhdg
i would be happy to help with the other plugins as well from time to time.

**Comment by rfscholte** [comment]
Okay, let's do the following: Sylwester will revert the commit. 
Next I'll make you a member of mojohaus
Than you can add your own key, that way the commit history is back to how we want it

**Comment by stefanseifert** [comment]
thanks!

**Comment by slachiewicz** [comment]
the commit has been reverted https://github.com/mojohaus/mojohaus.github.io/commit/b509b683e9e81d8c2344be66ef2eb1a0fbda8de3

**Pull request merged**
