### PR TITLE
Add Lasse Lindqvist to KEYS

### PR DESCRIPTION
**Pull request by lasselindqvist**
Add Lasse Lindqvist to KEYS

### CODE REVIEW

**Review by andham — APPROVED** [review]
Should be good. If you have the appropriate privs you can commit/merge yourself.

**Comment by lasselindqvist** [comment]
I have write access only to https://github.com/mojohaus/flatten-maven-plugin so someone else needs to merge this.

**Comment by bmarwell** [comment]
@lasselindqvist can you please rebase your PR?

**Comment by lasselindqvist** [comment]
This key already expired while waiting for merging, so I will just close this PR.

**Pull request closed without merging**
