### PR TITLE
[#39] remove dead link 'signatures'

### LINKED ISSUE #39: remove dead link "API signatures"
Probably a link to the animal sniffer plugin, which has its own menu item.

### PR DESCRIPTION
**Pull request by bmarwell**
fixes #39 

Has always been dead according to the way back machine.

### CODE REVIEW

**Comment by hboutemy** [comment]
yes, and this is a part or Animal Sniffer
something should be done about it, ideally more than just dropping the link, but fix the missing part, which would be useful

looking at https://repo.maven.apache.org/maven2/org/codehaus/mojo/signature/
I found https://repo.maven.apache.org/maven2/org/codehaus/mojo/signature/signatures-parent/1.2/

I will try to import the old svn: perhaps it's not so complex, I migrated old content in the past...

**Comment by hboutemy** [comment]
using instructions in https://github.com/mojohaus/convert-to-git
there are many signatures projects to migrate to Git, `signatures-parent` being the project that defines the main website:
```
$ docker run --rm batmat/mojohaus-converter svn ls file:///mojohaus-svn-repo/trunk/signatures/
graveyard/
j2ee14/
java12/
java12-sun/
java13/
java13-ibm/
java13-sun/
java14/
java14-ibm/
java14-jrockit/
java14-sun/
java15/
java15-harmony/
java15-ibm/
java15-jrockit/
java15-sun/
java16/
java16-apple/
java16-ibm/
java16-jrockit/
java16-sun/
java17/
javaee5/
sandbox/
signatures-parent/
```

I think that I will import to Git:
1. the `signatures-parent` content as `signatures.git`
2. every other one as `signature-xxx.git`

WDYT?

**Comment by hboutemy** [comment]
another simpler option would be to import everything as only one repository: not as precise, but given it's not really to revive Animal Sniffer signatures, perhaps it could be sufficient

**Comment by hboutemy** [comment]
I prepared a single `signatures` conversion: https://github.com/hboutemy/signatures
I can push content to MojoHaus...

**Comment by aheritier** [comment]
+1 with your migration proposal @hboutemy

**Comment by bmarwell** [comment]
+1, didn't know and this. The link has always been dead.

**Comment by hboutemy** [comment]
repository moved to MojoHaus
now, we need to create a basic site that mixes signatures-parent content and instructions from one signature file...

**Comment by hboutemy** [comment]
signatures site initialized http://www.mojohaus.org/signatures/

**Comment by bmarwell** [comment]
So can we close this PR?

**Pull request closed without merging**
